[package]
name = "angulus"
version = "0.3.0"
edition = "2021"
rust-version = "1.61"
authors = ["Tristan Guichaoua"]
description = "Unit agnostic angle"
keywords = ["utility", "angle", "math", "wrapper"]
categories = ["data-structures", "mathematics", "value-formatting"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/tguichaoua/angulus"

exclude = [".github/"]

[dependencies]
rand = { version = "0.8", optional = true, default-features = false }
serde = { version = "1", optional = true }

[dev-dependencies]
float_eq = "1"
rand = { version = "0.8", default-features = false, features = ["std", "std_rng"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
