[package]
name = "angulus"
version = "0.1.0"
edition = "2021"
authors = ["Tristan Guichaoua"]
description = "A wrapper for angle with unit convertion"
keywords = ["utility", "angle", "math", "wrapper"]
categories = ["data-structures", "mathematics", "value-formatting"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/tguichaoua/angulus"

exclude = [".github/"]

[dependencies]
serde = {version = "1", optional = true}

[dev-dependencies]
serde = {version = "1", features = ["derive"]}
serde_json = "1"
