name: CI

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    name: Test Rust ${{ matrix.toolchain }}
    strategy:
      matrix:
        toolchain: ['stable', 'beta', 'nightly']
    continue-on-error: ${{ matrix.toolchain != 'stable' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}

      - run: cargo test

      - name: No default features
        run: cargo check --no-default-features

      - name: All features
        run: cargo check --all-features

      - name: no_std
        run: cargo check --no-default-features --features=libm

      - name: no_std all features
        run: cargo check --no-default-features --features=libm,rand,serde

  msrv:
    name: 'Check MSRV: 1.61.0'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.61

      - name: Default features
        run: cargo check --all-targets

      - name: All features
        run: cargo check --all-targets --all-features

      - name: No-default features
        run: cargo check --all-targets --no-default-features

  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - name: Check documentation
        env:
          RUSTDOCFLAGS: -D warnings
        run: cargo doc --all-features --no-deps --document-private-items

  rustfmt:
    name: rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - run: cargo fmt --all --check

  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - run: cargo clippy --all-features -- -D warnings
